---
- hosts: all
  gather_facts: false
  connection: local

  vars:
    max_retries: 9
    retry_interval: 20
  
  vars_prompt:
    - name: "vmname"
      prompt: "Enter vmname"
      private: no

  tasks:
    - name: Debug vmname
      debug:
        var: vmname
