---
- hosts: localhost
  gather_facts: false
  connection: local
  
  # vars_prompt:
  #   - name: "vmname"
  #     prompt: "Enter vmname"
  #     private: no

  tasks:
    - name: Display variable vmname
      debug: 
        var: vmname

